### ISSUE TITLE
You

### ISSUE THREAD

**Issue by DylanShokrpour** [rgbeans/DoublePendulumSFML#3]
I have an issue with you Mr Pavokskie

**Comment by Ryan-000** [comment]
For reals bro he wont merge my PR bro

**Comment by Ryan-000** [comment]
Dear Dean,

I hope this message finds you well and thriving. I'm reaching out today to discuss something that's been weighing heavily on my heart. It's about the pull request (PR) I recently submitted to the GitHub repository you maintain. I understand how busy you are and truly appreciate the hard work you put into maintaining the repository. It's not just a collection of code; it's a thriving community that benefits from your dedication and expertise.

When I first discovered the project, I was incredibly excited. It felt like a place where I could contribute, learn, and collaborate with like-minded individuals. That's why, when I encountered an issue I thought I could help resolve, I didn't hesitate to get to work on a solution. I spent countless hours poring over the code, ensuring my solution was robust, efficient, and aligned with the project's standards. It was a labor of love, driven by my respect for the community you've built and my desire to contribute something meaningful.

Submitting the PR was a moment of pride for me. It represented not just a potential fix for an issue but my hope to become a more integral part of the community. That's why, when I saw that the PR was closed without being merged, I felt a profound sense of disappointment. More than that, I felt as though my efforts and enthusiasm were dismissed, which, I'll be honest, hurt quite a bit.

I understand that there might have been reasons for the decision that I'm not aware of. Perhaps there were concerns about the code's compatibility or its impact on other parts of the project. I'm fully open to feedback and willing to make any adjustments needed. My primary goal has always been to contribute positively to the project, and I'm ready to work harder to ensure my contributions meet the necessary standards.

I'm writing to kindly ask if you would reconsider the decision to close my PR. I genuinely believe that the changes I proposed could be beneficial for the project. Of course, I'm more than willing to discuss any concerns you might have or explore alternative solutions that might be more in line with the project's current needs and future direction.

I also want to express that my feelings of disappointment are not just about the PR itself but about what it represents—the opportunity to collaborate and contribute to something bigger than myself. Your guidance and feedback would be invaluable to me, not just in refining my current contribution but in helping me grow as a developer and community member.

To ensure that my future contributions are more in line with the project's needs, I would appreciate any guidance or suggestions you could offer. Whether it's areas of the code that require attention, specific project guidelines I should focus on, or resources that could help me improve my understanding and skills, I'm eager to learn and adapt.

In closing, I want to reiterate my respect and admiration for the work you do in maintaining the repository. It's a significant responsibility, and the project's success is a testament to your dedication and skill. My only wish is to be a part of that success, contributing in any way I can to the project's growth and the community's vibrancy.

Thank you for considering my request and for taking the time to read this message. I'm looking forward to your feedback and, hopefully, to the opportunity to work together towards making the project even better.

Warmest regards,

**Comment by rgbeans** [comment]
can you guys stop messing around on my GitHub? the universities I applied to and future employers can see this

**Comment by DylanShokrpour** [comment]
Fix our issues than we talk bro.

**Comment by Ryan-000** [comment]
@rgbeans 

I completely understand your concerns about maintaining a professional and respectful environment on your GitHub repository, especially considering its visibility to universities and potential employers. I apologize if our actions have caused any inconvenience or concern.

Regarding the issues we've been discussing, I'm more than happy to address them and work through any concerns you have. I believe a voice call could be a constructive way to discuss everything more thoroughly and find a path forward that benefits all parties involved.

I'm available tomorrow to talk about this in more detail. Please let me know a time that works best for you, and I'll make sure to accommodate. My goal is to resolve any outstanding issues in a manner that respects the integrity of your project and addresses any concerns you might have.

Thank you for your patience and understanding. I'm looking forward to our conversation and to finding a positive resolution.

Warm regards,
Ryan
